# Generated by Django 4.1.5 on 2023-02-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Number_of_SharerPassenger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
