# Generated by Django 4.1.5 on 2023-01-29 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_Address', models.CharField(max_length=100)),
                ('Earliest_Arrival_Time', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('Latest_Arrival_Time', models.DateTimeField(help_text='Format: 2020-01-01 13:00')),
                ('Number_of_Passenger', models.PositiveIntegerField(default=0)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_Address', models.CharField(max_length=100)),
                ('Arrival_Date_Time', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('Number_of_Passenger', models.PositiveIntegerField(default=1)),
                ('Vehicle_Type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('--', '--')], default='--', max_length=20)),
                ('Special_Request', models.CharField(blank=True, max_length=400)),
                ('Share_Or_Not', models.BooleanField()),
                ('Max_Share_Num', models.PositiveIntegerField(default=0, help_text='If you do not want to share please choose 0')),
                ('Status', models.CharField(default='Ongoing', max_length=20)),
                ('Sharers_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Driver_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Driver_License', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(max_length=20)),
                ('Vehicle_Type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('--', '--')], default='--', max_length=20)),
                ('Driver_License', models.CharField(default='', max_length=50)),
                ('Vehicle_Capacity', models.PositiveIntegerField(default=1)),
                ('Special_Information', models.CharField(blank=True, default='', max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
