# Generated by Django 4.1.5 on 2023-01-28 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_Address', models.CharField(max_length=100)),
                ('Arrial_Date_Time', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('Number_of_Passenger', models.PositiveIntegerField(default=1)),
                ('Vehicle_Type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('--', '--')], default='--', max_length=20)),
                ('Special_Request', models.CharField(blank=True, max_length=400)),
                ('Share_Or_Not', models.BooleanField()),
                ('max_share_num', models.PositiveIntegerField(default=0, help_text='If you do not want to share please choose 0')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
