# Generated by Django 4.1.5 on 2023-01-28 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerForm',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Arrial_Date_Time',
            new_name='Arrival_Date_Time',
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_Address', models.CharField(max_length=100)),
                ('Earliest_Arrival_Time', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('Latest_Arrival_Time', models.DateTimeField(help_text='Format: 2020-01-01 13:00')),
                ('Number_of_Passenger', models.PositiveIntegerField(default=0)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
