# Generated by Django 4.1.5 on 2023-01-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_ownerform_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='max_share_num',
            new_name='Max_Share_Num',
        ),
        migrations.AddField(
            model_name='owner',
            name='Driver_License',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='Driver_Name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='Share_Status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='Sharers_Name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
