# Generated by Django 4.1.5 on 2023-01-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_max_share_num_owner_max_share_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='Share_Status',
        ),
        migrations.AddField(
            model_name='owner',
            name='Status',
            field=models.CharField(default='Ongoing', max_length=20),
        ),
    ]
