# Generated by Django 4.1.5 on 2023-01-28 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_remove_owner_share_status_owner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('--', '--')], default='--', max_length=20)),
                ('Driver_License', models.CharField(blank=True, default='', max_length=50)),
                ('Vehicle_Capacity', models.PositiveIntegerField(default=1)),
                ('Special_Information', models.CharField(blank=True, default='', max_length=100)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
