# Generated by Django 4.1.5 on 2023-01-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Driver_Name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
