# Generated by Django 4.1.5 on 2023-01-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_driver_driver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='Driver',
            new_name='driver',
        ),
    ]
