# Generated by Django 4.1.5 on 2023-01-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_driver_driver_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Driver_Name',
            field=models.CharField(max_length=20),
        ),
    ]
