# Generated by Django 4.1.5 on 2023-01-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_driver_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Driver_License',
            field=models.CharField(default='', max_length=50),
        ),
    ]
